### ISSUE TITLE
Determine if a move is valid

### ISSUE THREAD

**Issue by ryicoh** [defuncart/shogi#15]

**Comment by defuncart** [comment]
Hi @ryicoh, thanks for checking out this package. Determining move validity is something that I'd like to add next. I'll be experimenting with bitboards on [this branch](https://github.com/defuncart/shogi/tree/feature/bitboard-game-representation). Unfortunately I do not have much free time at the moment, and I'm new to bitboards, so it'll probably take a while. Nevertheless I'll update this issue whenever I've something to report on :)
