### ISSUE TITLE
Convert GameBoard type to SFEN string

### ISSUE THREAD

**Issue by ryicoh** [defuncart/shogi#16]
Hi! Thank you for great package. :)

It may be implemented here. However, it does not export in `shogi.dart`.

https://github.com/defuncart/shogi/blob/d9a7722194d06309041571e379c95a38e7bd7364/lib/src/services/board_notation/sfen_converter.dart#L107

https://github.com/defuncart/shogi/blob/d9a7722194d06309041571e379c95a38e7bd7364/lib/shogi.dart#L1

**Comment by ryicoh** [comment]
@defuncart 
Thank you for merge my PR.
I'm looking forward to the next release!

**Comment by defuncart** [comment]
@ryicoh 0.0.6 has been released :) You may also be interested in [flutter_shogi_board](https://pub.dev/packages/flutter_shogi_board) package.
